### ISSUE TITLE
Two things, Ivo said wontfix, hoping you will

### ISSUE THREAD

**Issue by DLasher106** [passionate-coder/Classic-Start#38]
I submitted two issues on the Classic Shell forum a few years ago. Ivo rejected them, so I’ll give them another shot here.

1) The **Log Off [User]** menu text from StartMenuL10N.ini is:
`Menu.Logoff = &Log Off %s...` (in various languages).
I say that the “...” is wrong, because that logs you off _without_ a dialog box.

2) A feature request: the Start Button settings, **Classic button look**, currently allow you to change the button icon, icon size, and text; but the font and font size are hard-coded. I would appreciate a setting to change the font and font size.

Thanks!

**Comment by ibuprophen1** [comment]
I'm going to be honest with you (as a personal perspective)... 

I am understanding your issue in a 50/50 way. Basically, I understand half of it but, am being thrown off by the other half resulting in my questioning if I'm truly understanding this as a whole. 

I'm only commenting on this because I can perform various customizations within the software and many of those are the same/similar to each other but, are performed in different areas. 

I hope that I had explained this okay via text... 😵 

If it's something that I can do myself, i have no problem with providing a little guidance/help for you to accomplish this as well. 

Thank you very much for your patience and understanding with my question. 


~Ibuprophen

**Comment by XenHat** [comment]
@ibuprophen1 They have two combined issues. (I hate those! hahaha)

1. the `Log off` button label has a misleading `...` at the end of the string. Misleading because it doesn't actually spawn an additional input dialog, so there is no need for the `...` to exist at the end.
2. Logout/shutdown/power/etc. button (same one as above) can be customized on just about every aspect except for the **font family**, **font face** and **font size**.

**Comment by ibuprophen1** [comment]
Was this issue resolved with the commit you had pushed @XenHat? 


~Ibuprophen

**Comment by bonzibudd** [comment]
I think the logoff text needs to be tweaked a bit. Currently, if you enable the logoff dialog in OSM, the "..." string is still missing. It should be changed so that the option reflects whether or not you enable the logoff dialog.

Here's the option if anyone is confused:
![image](https://user-images.githubusercontent.com/61938331/98449525-466afd00-2102-11eb-975d-f3a9d88099e1.png)
